base_url: "https://practice.expandtesting.com/notes/app"
api_base_url: "https://practice.expandtesting.com/notes/api"
browser: "chrome"

implicit_wait: 5
explicit_wait: 15

email: "testuser2055@gmail.com"
password: "qwerty"

#execution_mode: "grid"
execution_mode: "local"
grid_url: "http://localhost:4444/wd/hub"