base_url: "https://practice.expandtesting.com/notes/app"
api_base_url: "https://practice.expandtesting.com/notes/api"
browser: "chrome"

implicit_wait: 35
explicit_wait: 35

email: "testuser2055@gmail.com"
password: "qwerty"

execution_mode: "local"
#execution_mode: "grid"
headless: false

grid_url: "http://localhost:4444/wd/hub"